
data:
  extract:
    enable: 0
    merge: ["tstrip", "sheeblimp"] # whatever name is first will be merged all into this
    ignore: ["isaacbarzso", "Maki", "Alistair", "Craig"]
    clean: True
    dir:
      raw: data/raw
      extracted: data/extracted
      zip_relpath: Craig

  split:
    enable: 0
    ignore: []
    max_splits: 500 # stop after we process more than 500 splits per speaker
    progress: True
    verbose: False
    accurate: False
    clean: False
    out_format: wav # sentences will be in this final format       
    sample_rate_hz: 22050
    num_channels: 1 # mono
    silence_db: -40
    min_silence_s: 2
    min_nonsilence_s: 2
    dir:
      processed: data/processed
      speaker: data/raw/speaker


  transcribe:
    enable: 0
    model: turbo
    verbose: True
    min_confidence: -0.5 # avglogprob minimum, otherwise discard it
    del_wav_if_no_transcribe: True
    ignore: []
    dir:
      # speaker: /content/drive/MyDrive/cloneai/processed # google collab
      processed: data/processed # local

model:
  tacotron2:
    test_split: 0.5
    enable: 1
    dir:
      processed: data/processed/2-scott
    args:
      n_gpus: 1,
      output_dir: "./outdir"
      log_dir: "./logdir"
      checkpoint_path: "./state_dict_tacotron2.pt"
      rank: 0
      warm_start: True
      group_name: "group_name"

    
    