
data:
  extract:
    enable: 0
    merge: ["tstrip", "sheeblimp"] # whatever name is first will be merged all into this
    ignore: ["isaacbarzso", "Maki", "Alistair", "Craig"]
    clean: False
    dir:
      raw: data/raw
      extracted: data/extracted

  split:
    ignore: ["idontseeit", "tstrip"]
    progress: True
    accurate: False
    enable: 1
    clean: False
    out_format: aac # sentences will be in this final format       
    sample_rate_hz: 44100
    silence_db: -40
    min_silence_s: 2
    min_nonsilence_s: 2
    dir:
      processed: data/processed
      speaker: data/raw/speaker


  transcribe:
    enable: 0
    model: turbo
    min_confidence: -0.5 # avglogprob minimum, otherwise discard it
    ignore: []
    dir:
      speaker: /content/drive/MyDrive/cloneai/processed # google collab
      # speaker: data/raw/speaker # local

    