
data:
  extract:
    enable: 1
    merge: ["tstrip", "sheeblimp"] # whatever name is first will be merged all into this
    ignore: ["isaacbarzso", "Maki", "Alistair", "Craig"]
    clean: False # delete zipped archives as we extract
    input_zip: raw-small.zip # relative to 'in' directory below
    dir:
      in: data/raw # relative to main workspace
      out: data/extracted

  split:
    enable: 0
    ignore: []
    max_splits: 500 # stop after we process more than 500 splits per speaker
    progress: True
    verbose: False
    accurate: False
    clean: False
    out_format: wav # sentences will be in this final format       
    sample_rate_hz: 22050
    num_channels: 1 # mono
    silence_db: -40
    min_silence_s: 2
    min_nonsilence_s: 2
    dir:
      speaker: data/raw/speaker
      processed: data/processed

  transcribe:
    enable: 0
    model: turbo
    verbose: True
    min_confidence: -0.5 # avglogprob minimum, otherwise discard it
    del_wav_if_no_transcribe: True
    ignore: []
    dir:
      in: data/processed # local



    
    